name: main

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        zabbix-server-versions: [
          '5.0',
          '5.2',
        ]
    env:
      ANSIBLE_CONFIG: .github/workflows/ansible.cfg
    name: test-zabbix-${{ matrix.zabbix-server-versions }}
    steps:
      - name: show operating system information
        run: lsb_release -a

      - uses: actions/checkout@v2

      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install ansible
        run: sudo pip3 install wheel && sudo pip3 install -r .github/workflows/requirements.txt

      - name: install required ansible collections
        run: sudo ansible-galaxy collection install community.zabbix

      - name: show python version
        run: sudo python3 --version

      - name: show ansible version
        run: sudo ansible --version

      - name: setup zabbix server using ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          inventory: localhost
          playbook: .github/workflows/ansible-playbook-configure-zabbix-server.yml
          options: -e "zabbix_server_version=${{ matrix.zabbix-server-versions }}"

      - name: show zabbix server version
        run: sudo zabbix_server --version

      - name: import template to zabbix server using ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          inventory: localhost
          playbook: .github/workflows/ansible-playbook-import-template.yml
